services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOVIES_PATH}:/media/movies
      - ${RADARR_CONFIG}:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${RADARR_PORT}:7878
    network_mode: synobridge
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}:/media
      - ${JELLYFIN_LOG}:/log
      - ${JELLYFIN_DATA}:/data
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_CACHE}:/cache
    ports:
      - ${JELLYFIN_PORT}:8096
    devices:
      - /dev/dri:/dev/dri
    network_mode: synobridge
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TV_PATH}:/media/tv
      - ${ANIME_PATH}:/media/anime
      - ${SONARR_CONFIG}:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${SONARR_PORT}:8989
    network_mode: synobridge
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${TV_PATH}:/media/tv
      - ${ANIME_PATH}:/media/anime
      - ${MOVIES_PATH}:/media/movies
      - ${BAZARR_CONFIG}:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${BAZARR_PORT}:6767
    network_mode: synobridge
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG}:/config
    ports:
      - ${PROWLARR_PORT}:9696
    network_mode: synobridge
    restart: unless-stopped

  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}/audiobooks:/media/audiobooks:rw
      - ${MEDIA_PATH}/podcasts:/media/podcasts
      - ${AUDIOBOOKSHELF_CONFIG}:/config:rw
      - ${AUDIOBOOKSHELF_METADATA}:/metadata:rw
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    network_mode: synobridge
    restart: unless-stopped

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}/books:/media/books
      - ${MEDIA_PATH}/comics:/media/comics
      - ${MEDIA_PATH}/manga:/media/manga
      - ${KAVITA_CONFIG}:/kavita/config
    ports:
      - ${KAVITA_PORT}:5000
    network_mode: synobridge
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - ${JELLYSEERR_CONFIG}:/app/config
    ports:
      - ${JELLYSEERR_PORT}:5055
    network_mode: synobridge
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - TZ=${TZ}
    volumes:
      - ${HOMARR_CONFIG}:/app/data/configs
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_CONFIG}:/app/data/configs
      - ${HOMARR_ICONS}:/app/public/icons
      - ${HOMARR_DATA}:/data
    ports:
      - ${HOMARR_PORT}:7575
    network_mode: synobridge
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_PORT_UI}
      - UMASK=002
    volumes:
      - ${QBITTORRENT_CONFIG}:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/tcp
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp
      - ${QBITTORRENT_PORT_UI}:8090
    network_mode: synobridge
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 4 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: synobridge
    restart: unless-stopped

  subsyncarr:
    image: mrorbitman/subsyncarr:latest
    container_name: subsyncarr
    volumes:
      - ${MEDIA_PATH}:/scan_dir
    restart: unless-stopped

  fileflows:
    image: revenz/fileflows:stable
    container_name: fileflows
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TempPathHost=${FILEFLOWS_TEMP}
    volumes:
      - ${MEDIA_PATH}:/media
      - ${DOWNLOADS_PATH}:/downloads
      - ${MOVIES_PATH}:/videos
      - ${FILEFLOWS_TEMP}:/temp
      - ${FILEFLOWS_DATA}:/app/Data
      - ${FILEFLOWS_LOGS}:/app/Logs
      - ${FILEFLOWS_COMMON}:/app/common
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${FILEFLOWS_PORT}:5000
    devices:
      - /dev/dri:/dev/dri
    network_mode: synobridge
    restart: unless-stopped

