services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MOVIES_PATH}:/media/movies
      - ${CONFIG_PATH}/radarr:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${RADARR_PORT}:7878
    network_mode: synobridge
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}:/media
      - ${CONFIG_PATH}/jellyfin/log:/log
      - ${CONFIG_PATH}/jellyfin/data:/data
      - ${CONFIG_PATH}/jellyfin/config:/config
      - ${CONFIG_PATH}/jellyfin/cache:/cache
    ports:
      - ${JELLYFIN_PORT}:8096
    devices:
      - /dev/dri:/dev/dri
    network_mode: synobridge
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TV_PATH}:/media/tv
      - ${ANIME_PATH}:/media/anime
      - ${CONFIG_PATH}/sonarr:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${SONARR_PORT}:8989
    network_mode: synobridge
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TV_PATH}:/media/tv
      - ${ANIME_PATH}:/media/anime
      - ${MOVIES_PATH}:/media/movies
      - ${CONFIG_PATH}/bazarr:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${BAZARR_PORT}:6767
    network_mode: synobridge
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    network_mode: synobridge
    restart: unless-stopped

  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}/audiobooks:/media/audiobooks:rw
      - ${MEDIA_PATH}/podcasts:/media/podcasts
      - ${CONFIG_PATH}/audiobookshelf/config:/config:rw
      - ${CONFIG_PATH}/audiobookshelf/metadata:/metadata:rw
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    network_mode: synobridge
    restart: unless-stopped

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}/books:/media/books
      - ${MEDIA_PATH}/comics:/media/comics
      - ${MEDIA_PATH}/manga:/media/manga
      - ${CONFIG_PATH}/kavita:/kavita/config
    ports:
      - ${KAVITA_PORT}:5000
    network_mode: synobridge
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    ports:
      - ${JELLYSEERR_PORT}:5055
    network_mode: synobridge
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/homarr:/app/data/configs
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/homarr/configs:/app/data/configs
      - ${CONFIG_PATH}/homarr/icons:/app/public/icons
      - ${CONFIG_PATH}/homarr/data:/data
    ports:
      - ${HOMARR_PORT}:7575
    network_mode: synobridge
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_PORT_UI}
      - UMASK=002
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/tcp
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp
      - ${QBITTORRENT_PORT_UI}:8090
    network_mode: synobridge
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 4 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: synobridge
    restart: unless-stopped
